sonar.organization=spooky312
sonar.projectKey=ict2216-cvbuilder
sonar.projectName=ICT2216 CVBuilder
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=**/__pycache__/**,**/migrations/**,**/.pytest_cache/**,**/node_modules/**,**/dist/**,**/build/**
