sonar.projectKey=ict2216-cvbuilder-flask
sonar.projectName=ICT2216 CVBuilder Flask Backend
sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=**/__pycache__/**,**/migrations/**,**/.pytest_cache/**