"""auto

Revision ID: 16d0388af711
Revises: d2f4a6b8c901
Create Date: 2026-06-22 20:24:02.270439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d0388af711'
down_revision = 'd2f4a6b8c901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('revoked_tokens_jti_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('revoked_tokens_jti_key'), ['jti'])

    # ### end Alembic commands ###
